{
 "title": "GrayLog-Nodes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Filter Execution(Incoming)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Filter Execution" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Filter execution Time(Incoming Messages) 5min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Filter Execution(Incoming)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Filter Execution" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Filter execution Time(Incoming Messages) 5min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Internal Log Message(Error)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Internal Log" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Internal Log Message Error 5 min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Internal Log Message(Warn)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Internal Log" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Internal Log Message Warn 5 min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Node Processing",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "Graylog: Node Status" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "Graylog: Node Processing" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog Service" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "GrayLog: Service Status" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Node Lifecycle",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "Graylog: Node Status" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "Graylog: Node Lifecycle" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Node Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 2 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "Graylog: Node Status" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "Graylog: Node Status" },
     "mode": 2,
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Filter Execution(Filtered)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Filter Execution" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Filter execution Time(FIltered OutMessages) 5min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Filter Execution(OutGoing)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Filter Execution" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Filter execution Time(Outgoing Message) 5min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Internal Log Message ( Fatal)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Internal Log" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "GrayLog: Internal Log Message Fatal 5 min"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Journal Size",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "GrayLog: Journal" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "GrayLog Journal Size" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Free Disk",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "Filesystems" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": {
      "filter": "Free disk space on / (percentage)"
     },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "application": { "filter": "Performance" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "Processo Load (5 min)" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Graylog: Node Memory" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "GrayLog: Node Free Memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Graylog: Node Memory" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "GrayLog: Node Max Memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Graylog: Node Memory" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "GrayLog: Node Used Memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    },
    {
     "application": { "filter": "Graylog: Node Memory" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "GrayLog: Node Total Memory" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "application": { "filter": "Network interfaces" },
     "group": { "filter": "Onx Solutions" },
     "host": { "filter": "Onx-Graylog-EC" },
     "item": { "filter": "" },
     "options": {
      "showDisabledItems": false,
      "skipEmptyValues": false
     },
     "table": {
      "skipEmptyValues": false
     },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  }
 ]
}